export const PROJECTS = [
  {
    id: 1,
    title:
      '프로젝트 A프로젝트 A프로젝트 A프로젝트 A프로젝트 A프로젝트 A프로젝트 A프로젝트 A프로젝트 A',
    techStack: ['React', 'Node.js', 'MongoDB'],
    authorProfile: '/path/to/profile1.png',
    authorNickname: '작성자1',
    likes: 120,
    views: 450,
  },
  {
    id: 2,
    title:
      '프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B프로젝트 B',
    techStack: ['Vue.js', 'Express', 'MySQL'],
    authorProfile: '/path/to/profile2.png',
    authorNickname: '작성자2',
    likes: 85,
    views: 300,
  },
  {
    id: 3,
    title: '프로젝트 C',
    techStack: [
      'Angular',
      'Django',
      'PostgreSQL',
      'Vue.js',
      'Express',
      'MySQL',
    ],
    authorProfile: '/path/to/profile3.png',
    authorNickname: '작성자3',
    likes: 60,
    views: 200,
  },
  {
    id: 4,
    title: '프로젝트 D',
    techStack: ['Svelte', 'Firebase'],
    authorProfile: '/path/to/profile4.png',
    authorNickname: '작성자4',
    likes: 150,
    views: 500,
  },
  {
    id: 5,
    title: '프로젝트 E',
    techStack: ['Next.js', 'Supabase'],
    authorProfile: '/path/to/profile5.png',
    authorNickname: '작성자5',
    likes: 95,
    views: 350,
  },
  {
    id: 6,
    title: '프로젝트 F',
    techStack: ['Nuxt.js', 'Laravel', 'MySQL'],
    authorProfile: '/path/to/profile6.png',
    authorNickname: '작성자6',
    likes: 70,
    views: 220,
  },
  {
    id: 7,
    title: '프로젝트 G',
    techStack: ['Remix', 'Prisma', 'PostgreSQL'],
    authorProfile: '/path/to/profile7.png',
    authorNickname: '작성자7',
    likes: 110,
    views: 400,
  },
  {
    id: 8,
    title: '프로젝트 H',
    techStack: ['Astro', 'GraphQL'],
    authorProfile: '/path/to/profile8.png',
    authorNickname: '작성자8',
    likes: 80,
    views: 280,
  },
  {
    id: 9,
    title: '프로젝트 I',
    techStack: ['Solid.js', 'FastAPI'],
    authorProfile: '/path/to/profile9.png',
    authorNickname: '작성자9',
    likes: 65,
    views: 190,
  },
]
