import { Project } from '@/types/project'

export const PROJECTS: Project[] = [
  {
    id: 1,
    title: '프로젝트 A',
    description: '프로젝트 A에 대한 간단한 설명',
    stack: ['React', 'Node.js', 'MongoDB'],
    deadline: '2025-12-31',
    author: {
      id: 1,
      email: 'author1@example.com',
      nickname: '작성자1',
      bio: '프로젝트 A의 작성자',
      writtenPosts: [], // 작성한 게시글들을 여기에 추가
      appliedPosts: [], // 신청한 게시글들을 여기에 추가
    },
    likes: 120,
    views: 450,
    createdAt: '2025-01-01',
    updatedAt: '2025-02-01',
  },
  {
    id: 2,
    title: '프로젝트 B',
    description: '프로젝트 B에 대한 간단한 설명',
    stack: ['Vue.js', 'Express', 'MySQL'],
    deadline: '2025-06-30',
    author: {
      id: 2,
      email: 'author2@example.com',
      nickname: '작성자2',
      bio: '프로젝트 B의 작성자',
      writtenPosts: [],
      appliedPosts: [],
    },
    likes: 85,
    views: 300,
    createdAt: '2025-02-01',
    updatedAt: '2025-03-01',
  },
  {
    id: 3,
    title: '프로젝트 C',
    description: '프로젝트 C에 대한 간단한 설명',
    stack: ['Angular', 'Django', 'PostgreSQL', 'Vue.js', 'Express', 'MySQL'],
    deadline: '2025-05-31',
    author: {
      id: 3,
      email: 'author3@example.com',
      nickname: '작성자3',
      bio: '프로젝트 C의 작성자',
      writtenPosts: [],
      appliedPosts: [],
    },
    likes: 60,
    views: 200,
    createdAt: '2025-03-01',
    updatedAt: '2025-04-01',
  },
  {
    id: 4,
    title: '프로젝트 D',
    description: '프로젝트 D에 대한 간단한 설명',
    stack: ['Svelte', 'Firebase'],
    deadline: '2025-07-15',
    author: {
      id: 4,
      email: 'author4@example.com',
      nickname: '작성자4',
      bio: '프로젝트 D의 작성자',
      writtenPosts: [],
      appliedPosts: [],
    },
    likes: 150,
    views: 500,
    createdAt: '2025-04-01',
    updatedAt: '2025-05-01',
  },
  {
    id: 5,
    title: '프로젝트 E',
    description: '프로젝트 E에 대한 간단한 설명',
    stack: ['Next.js', 'Supabase'],
    deadline: '2025-08-01',
    author: {
      id: 5,
      email: 'author5@example.com',
      nickname: '작성자5',
      bio: '프로젝트 E의 작성자',
      writtenPosts: [],
      appliedPosts: [],
    },
    likes: 95,
    views: 350,
    createdAt: '2025-05-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 6,
    title: '프로젝트 F',
    description: '프로젝트 F에 대한 간단한 설명',
    stack: ['Nuxt.js', 'Laravel', 'MySQL'],
    deadline: '2025-09-10',
    author: {
      id: 6,
      email: 'author6@example.com',
      nickname: '작성자6',
      bio: '프로젝트 F의 작성자',
      writtenPosts: [],
      appliedPosts: [],
    },
    likes: 70,
    views: 220,
    createdAt: '2025-06-01',
    updatedAt: '2025-07-01',
  },
  {
    id: 7,
    title: '프로젝트 G',
    description: '프로젝트 G에 대한 간단한 설명',
    stack: ['Remix', 'Prisma', 'PostgreSQL'],
    deadline: '2025-10-20',
    author: {
      id: 7,
      email: 'author7@example.com',
      nickname: '작성자7',
      bio: '프로젝트 G의 작성자',
      writtenPosts: [],
      appliedPosts: [],
    },
    likes: 110,
    views: 400,
    createdAt: '2025-07-01',
    updatedAt: '2025-08-01',
  },
  {
    id: 8,
    title: '프로젝트 H',
    description: '프로젝트 H에 대한 간단한 설명',
    stack: ['Astro', 'GraphQL'],
    deadline: '2025-11-01',
    author: {
      id: 8,
      email: 'author8@example.com',
      nickname: '작성자8',
      bio: '프로젝트 H의 작성자',
      writtenPosts: [],
      appliedPosts: [],
    },
    likes: 80,
    views: 280,
    createdAt: '2025-08-01',
    updatedAt: '2025-09-01',
  },
  {
    id: 9,
    title: '프로젝트 I',
    description: '프로젝트 I에 대한 간단한 설명',
    stack: ['Solid.js', 'FastAPI'],
    deadline: '2025-12-01',
    author: {
      id: 9,
      email: 'author9@example.com',
      nickname: '작성자9',
      bio: '프로젝트 I의 작성자',
      writtenPosts: [],
      appliedPosts: [],
    },
    likes: 65,
    views: 190,
    createdAt: '2025-09-01',
    updatedAt: '2025-10-01',
  },
]
