export const STUDIES = [
  {
    id: 1,
    title:
      '스터디 A스터디 A스터디 A스터디 A스터디 A스터디 A스터디 A스터디 A스터디 A스터디 A',
    authorProfile: '/path/to/profile1.png',
    authorNickname: '작성자1',
    likes: 120,
    views: 450,
  },
  {
    id: 2,
    title:
      '스터디 B스터디 B스터디 B스터디 B스터디 B스터디 B스터디 B스터디 B스터디 B스터디 B스터디 B스터디 B스터디 B스터디 B스터디 B스터디 B스터디 B스터디 B스터디 B스터디 B스터디 B스터디 B',
    authorProfile: '/path/to/profile2.png',
    authorNickname: '작성자2',
    likes: 85,
    views: 300,
  },
  {
    id: 3,
    title: '스터디 C',
    authorProfile: '/path/to/profile3.png',
    authorNickname: '작성자3',
    likes: 60,
    views: 200,
  },
  {
    id: 4,
    title: '스터디 D',
    authorProfile: '/path/to/profile4.png',
    authorNickname: '작성자4',
    likes: 150,
    views: 500,
  },
  {
    id: 5,
    title: '스터디 E',
    authorProfile: '/path/to/profile5.png',
    authorNickname: '작성자5',
    likes: 95,
    views: 350,
  },
  {
    id: 6,
    title: '스터디 F',
    authorProfile: '/path/to/profile6.png',
    authorNickname: '작성자6',
    likes: 70,
    views: 220,
  },
  {
    id: 7,
    title: '스터디 G',
    authorProfile: '/path/to/profile7.png',
    authorNickname: '작성자7',
    likes: 110,
    views: 400,
  },
  {
    id: 8,
    title: '스터디 H',
    authorProfile: '/path/to/profile8.png',
    authorNickname: '작성자8',
    likes: 80,
    views: 280,
  },
  {
    id: 9,
    title: '스터디 I',
    authorProfile: '/path/to/profile9.png',
    authorNickname: '작성자9',
    likes: 65,
    views: 190,
  },
]
